#!/usr/bin/env sh

# Installs dotfile packages using stow

# Exit on non-zero status.
set -e
# Exit on undefined variable.
set -u
# Xtrace. Print executed commands.
#set -x

SCRIPT_FILE=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_FILE")
STOW_PACKAGES_DIR=${SCRIPT_DIR}/packages
STOW_TARGET_DIR=$HOME


for package in ${STOW_PACKAGES_DIR}/*/
do
    package=${package%*/}  # remove the trailing "/"
    package=${package##*/}  # get everything after the final "/"
    echo "Installing package '${package}'..."

    stow \
        -d "${STOW_PACKAGES_DIR}" \
        -t "${STOW_TARGET_DIR}" \
        -vv \
        "$package"
    echo
done
